### ISSUE TITLE
Add WebPageTest link when too big

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/custom-metrics#146]
At the moment when the test results are too big for the comment we add this:

> Webpage test results that are too big for a comment are available as [the action's artifact](https://github.com/HTTPArchive/custom-metrics/actions/runs/10973750435/artifacts/1961803918).

Example:
https://github.com/HTTPArchive/custom-metrics/pull/145#issuecomment-2365230655

It would be nice if we also got a WebPageTest link so we can see them there too. Is this possible @max-ostapenko ?

**Comment by max-ostapenko** [comment]
When I download and open the artifact the URL is there:
![Screenshot 2024-09-21 at 21 04 44](https://github.com/user-attachments/assets/612748c6-c6e6-48df-8d4e-54b5bad3d7a2)

Or did you mean something else?

**Comment by tunetheweb** [comment]
I mean putting the test URL link in the GitHub comment as well.

That would allow me to click on it to copy and waste the custom metric rather than having to download and unzip a file.
