### ISSUE TITLE
Investigate impact of first response body not being HTML

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/custom-metrics#15]
Some custom metrics rely on `$WPT_BODIES[0]` being the main HTML document. However, we've seen some edge cases (on up to 15% of pages) where the first request does not correspond to the main document. These custom metrics would assumedly be processing the data for the wrong response body.

Investigate whether this is actually happening and how to fix it, if so.

**Comment by rviscomi** [comment]
It doesn't seem like the `$WPT_BODIES` object is affected by this issue.

[Here](https://webpagetest.httparchive.org/result/220402_Dx90_HKKF/1/details/#waterfall_view_step1) is a test from the 2022_04_01_desktop crawl in which the URL was incorrectly parsed as `http://cacerts.digitalcertvalidation.com/TrustAsiaTLSRSACA.crt`. The request at `entries[0]` in the HAR corresponds to the certificate and `_is_base_page` is set to true.

```json
{
    "_full_url": "http://cacerts.digitalcertvalidation.com/TrustAsiaTLSRSACA.crt",
    "_is_base_page": true,
    "_index": 0
}
```

I [reran](https://webpagetest.httparchive.org/result/220526_5P_9/1/details/#waterfall_view_step1) the test with a custom metric that outputs the full `$WPT_BODIES` object. The object schema is not quite the same as the HAR but it's clear that the first item is the HTML document itself, not the cert:

```json
{
    "url": "https://52.mk/",
    "type": "Document"
}
```

So I think we're ok.

**Comment by pmeenan** [comment]
The waterfall and main request data are post-processed using the netlog trace events.  The $WPT_BODIES (and $WPT_REQUESTS) use the dev tools request details which don't see things like OCSP checks so the first request should (hopefully) always be the actual navigation.
