### ISSUE TITLE
Performance 2022 custom metrics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/custom-metrics#16]
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/2890
## Antipatterns
- [x] LCP image source dynamically changed

Add a new custom metric to performance.js that detects whether the LCP image (if applicable) had its image source dynamically changed.

For example, if the raw HTML source was served as `<img data-src="cat.jpg">` but the fully-rendered LCP image was `<img src="cat.jpg">`, some kind of lazy-loading library seems to be at play.

## Gaming the Metrics
- [ ] Filtering for synthetic tests -  Add a new custom metric to performance.js that detects if there is any code in HTML response to filter some resources based on synthetic tests user agent such as lighthouse/GTmatrix. 
- [ ] LCP Animation & Overlay Hack - Detect if LCP element is 'hidden' by opacity animation. 
- [ ] LCP Svg Overlay Hack: Detect image tag at top of the body containing transparent SVG at 99vh & 99vw, with the `pointer-events: none` CSS style.
- [ ] CLS Animation Hack - Detect if layout shift element is 'hidden' by opacity animation
- [ ] FID iframe Hack - Detect if viewport is covered in transparent iframe -> after pageload event fires, iframe is removed. Will require adding a script to run before the page loads and comparing the initial response body with the DOM after page load (see [Rick's livestream](https://www.youtube.com/watch?v=71lA-p15NhI) for tutorial)
- [ ] [Nice to Have] LCP Element Render Delay - Number of sync resources (ResponseEnd time of resources (timestamp) < LCP resource startTime),  for LCP elements like H1 /any HTML tag, based on element HTML position

Note: The LCP Animation & CLS Animation metrics may be able to be combined. What if we scan for all elements that have this animation applied, and return something like this?
```{ numberOfElements: 6, isAppliedToLCPElement: true}```

cc @mel-ada @konfirmed @25prathamesh @silent1mezzo

**Comment by rviscomi** [comment]
In general that'd be really helpful to know that there was some delay in fetching. Would we be able to tell why fetching was delayed without further instrumentation like this?

**Comment by pmeenan** [comment]
You may be able to get some sense of "why" by looking at the initiator data to see if it was triggered by JS but I'm not sure how well the initiator catches all of the cases.

**Comment by rviscomi** [comment]
Ran a [test](https://webpagetest.httparchive.org/result/220524_4V_6/) of https://codepen.io/rviscomi/pen/mdXBJqY

```json
{
  "_initial_priority": "Low",
  "_initiator": "",
  "_initiator_column": "",
  "_initiator_line": "",
  "_initiator_type": "other",
  "_priority": "Low"
}
```

The other (immediately loaded) image has an `_initiator_type` value of `"parser"`. is that how you were thinking of distinguishing fetch delays?

**Comment by pmeenan** [comment]
The "type" should be good for if it was in the HTML or not (or the initiator URL itself as well).  `_initial_priority` of `Low` is also a sign of priority hints not being used.
