### ISSUE TITLE
Improve a11y metric for captioned tables

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/custom-metrics#19]
_Copied from https://github.com/HTTPArchive/legacy.httparchive.org/issues/248_

The Accessibility Chapter uses this custom metric code to find captioned table:

https://github.com/HTTPArchive/custom-metrics/blob/46b90e85e49516950ceed962dc13871ffc822731/dist/a11y.js#L47-L57

However some sites (like the Web Almanac itself!) uses `<figcaptions>` which [are a valid alternative](https://www.w3.org/WAI/tutorials/tables/caption-summary/). We should enhance this detection to capture this with the following code:

```js
const tables_with_figcaption = document.querySelectorAll('figure:has(table):has(figcaption)');
```

I've tested this in Chrome 96 and it works! 😀
But not in WPT as [not enabled by default until Chrome 105](https://chromestatus.com/feature/5794378545102848) - so can't add yet 😞

Twitter thread: https://twitter.com/tunetheweb/status/1462885130318589952?s=20

Adding an issue to remind myself to add once `:has()` is fully rolled out in Chrome 105

**Comment by rviscomi** [comment]
FYI you can use the "Transfer issue" button to handle moving issues across repos

<img width="162" alt="image" src="https://user-images.githubusercontent.com/1120896/169891887-a0ed9fde-30de-40b7-aa3d-c9341d5dd69a.png">

**Comment by tunetheweb** [comment]
TIL!
