### ISSUE TITLE
Issues with some new performance custom metrics

### ISSUE THREAD

**Issue by philipwalton** [HTTPArchive/custom-metrics#45]
I was taking a look at some of the custom metrics added in #20 and I noticed a few issues with the code:

1. [Line 260](https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L260) creates a URL from a `srcset` attribute, but `srcset` attributes contain multiple URLs that need to be parsed and iterated over, so this will never match. (See [this false negative](https://webpagetest.httparchive.org/result/220609_DxI7_3WGSH/) for an example failure case).
2. [Line 259](https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L259) only looks at `srcset` attributes in `<source>` elements, but images can also have `srcset` attributes.
3. [Line 265](https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L265): Images in preload tags are discoverable from the main document ([preload scanner](https://web.dev/preload-scanner/)), so I think this condition needs to be inclusive of cases where `isLcpPreloaded` is true.
4. [Line 267](https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L267): `<preload>` tags can also contain an `imagesrcset` attribute, so that needs to be checked as well (and it needs to be parsed, like in (1) above).
5. Also [Line 267](https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L267): preload hints can be set on HTTP headers, so just checking `<link>` element is not enough to know whether or not a resource was preloaded.

In addition to these issues, I'm also concern because (if I understand correctly) the custom metric code runs at the end of a test on the live DOM, which may not catch many of the antipatterns we're seeing around things like JS lazy loading of the LCP image.

For example, if an inline JS script replaces `data-src` attributes with `src` attributes for images determined to be within the viewport, I think this custom metric code would falsely determine that that resource was discoverable, which it actually wasn't, correct?

**Comment by rviscomi** [comment]
Thanks for filing this, agreed that these would be great enhancements to the accuracy of the metric. I've got a draft of the fixes in #46, pending additional testing.

> For example, if an inline JS script replaces `data-src` attributes with `src` attributes for images determined to be within the viewport, I think this custom metric code would falsely determine that that resource was discoverable, which it actually wasn't, correct?

The discoverable/preloaded checks actually use the initial document state, not the fully rendered DOM. `rawDoc` represents the DOM of the static HTML returned by the server.

https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L257

https://github.com/HTTPArchive/custom-metrics/blob/48865343b15d898b3c472d72a1327e50333f24cc/dist/performance.js#L266

**Comment by philipwalton** [comment]
> The discoverable/preloaded checks actually use the initial document state, not the fully rendered DOM. `rawDoc` represents the DOM of the static HTML returned by the server.

Ahh, good to know. Thanks!
