### ISSUE TITLE
All custom metrics are null for a given page

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/custom-metrics#63]
I stumbled upon a page in which every custom metric is null: `https://royal-st-york.com/`
WPT results: https://webpagetest.httparchive.org/result/221201_Dx1NT_CTH8N/1/details/

It seems like the cause was that the test timed out after 2 minutes. FWIW it also weighs about 68 MB (mostly images).

Is it possible to calculate the custom metrics before timing out?

**Comment by pmeenan** [comment]
Maybe.  It would have had the onload fired but for page loads that timeout before onload, WPT considers it a test failure and doesn't do any more in-browser processing.  I'll take a look but if the main thread is wedged it may introduce cases where the overall test timeout is reached and no data is collected.

**Comment by pmeenan** [comment]
Will be fixed in the Feb crawl.  Timeouts are now going to be treated as "soft" errors by the browser logic which will allow it to continue to execute js (collect custom metrics) and run a lighthouse audit.

**Comment by pmeenan** [comment]
Verified fixed: https://webpagetest.httparchive.org/result/230201_Mx1QZ_DHWHG/
